<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>lsc</string>
   </array>
  <key>name</key>
  <string>LuaScript</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.LuaScript</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>\b(constructor)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.LuaScript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.LuaScript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#lua</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#SELF</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#strings</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numbers</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(break|do| else|elseif|end|for|if|in|local|repeat|return|then|until|while)\b</string>
          <key>name</key>
          <string>keyword.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(#)(?=[\w\d._]+\b)</string>
          <key>name</key>
          <string>constant.numeric.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(nil|true|false|math.pi)\b</string>
          <key>name</key>
          <string>constant.numeric.LuaScript</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*(var)\b)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.LuaScript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.LuaScript</string>
          <key>end</key>
          <string>(=|$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.LuaScript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>\b(prototype\s+|struct\s+)([\w\d_\.]+)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.LuaScript</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.class.LuaScript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(def)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.LuaScript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.LuaScript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.LuaScript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.LuaScript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.LuaScript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>SELF</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>\b(self)\b</string>
          <key>name</key>
          <string>keyword.self.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.\.\.)</string>
          <key>name</key>
          <string>constant.numeric.LuaScript</string>
        </dict>
       </array>
    </dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\-\-\[\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.LuaScript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.LuaScript</string>
          <key>end</key>
          <string>(\-\-\]\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.LuaScript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\-\-)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.LuaScript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.LuaScript</string>
          <key>end</key>
          <string>($)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.LuaScript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>comments__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>comments__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>lua</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>\b(or|and|not)\b</string>
          <key>name</key>
          <string>keyword.operator.LuaScript</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(function)(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.LuaScript</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.LuaScript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#lua__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.LuaScript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(function\s+)([\w\d_\.]+)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.LuaScript</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.LuaScript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#lua__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.LuaScript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(\:?\.?)([\w\d_]+(?=\())</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.LuaScript</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.LuaScript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(\.)([\w\d_]+)\b</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.LuaScript</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.LuaScript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(assert|collectgarbage|dofile|error|getfenv|getmetatable|ipairs|loadfile|loadstring|module|next|pairs|pcall|print|rawequal|rawget|rawset|require|select|setfenv|setmetatable|tonumber|tostring|type|unpack|xpcall)\b(?=\[\[|\()</string>
          <key>name</key>
          <string>entity.name.function.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(coroutine\.(create|resume|running|status|wrap|yield)|string\.(byte|char|dump|find|format|gmatch|gsub|len|lower|match|rep|reverse|sub|upper)|table\.(concat|insert|maxn|remove|sort)|math\.(abs|acos|asin|atan2?|ceil|cosh?|deg|exp|floor|fmod|frexp|ldexp|log|log10|max|min|modf|pow|rad|random|randomseed|sinh?|sqrt|tanh?)|io\.(close|flush|input|lines|open|output|popen|read|tmpfile|type|write)|os\.(clock|date|difftime|execute|exit|getenv|remove|rename|setlocale|time|tmpname)|package\.(cpath|loaded|loadlib|path|preload|seeall)|debug\.(debug|[gs]etfenv|[gs]ethook|getinfo|[gs]etlocal|[gs]etmetatable|getregistry|[gs]etupvalue|traceback|upvaluejoin))\b(?=\s*(?:[\x\x{007b}0028\x{007d}\x\x{007b}007b\x{007d}\&amp;quot\x{003b}\x\x{007b}0027\x{007d}]|\[\[|\())</string>
          <key>name</key>
          <string>entity.name.function.LuaScript</string>
        </dict>
       </array>
    </dict>
    <key>lua__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#SELF</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+)</string>
          <key>name</key>
          <string>constant.numeric.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\()</string>
          <key>name</key>
          <string>text.LuaScript</string>
        </dict>
       </array>
    </dict>
    <key>lua__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#SELF</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+)</string>
          <key>name</key>
          <string>constant.numeric.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\()</string>
          <key>name</key>
          <string>text.LuaScript</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\w+)</string>
          <key>name</key>
          <string>constant.numeric.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\()</string>
          <key>name</key>
          <string>text.LuaScript</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>\b(\s+is\s+)([\w\d_\.]+)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.LuaScript</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>string.LuaScript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__5</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#lua</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#SELF</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#strings</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numbers</string>
        </dict>
       </array>
    </dict>
    <key>numbers</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(0[xX][0-9a-fA-F]+)</string>
          <key>name</key>
          <string>constant.numeric.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\-\d*\.?\d+|\b\d*\.?\d+)</string>
          <key>name</key>
          <string>constant.numeric.LuaScript</string>
        </dict>
       </array>
    </dict>
    <key>strings</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.LuaScript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#strings__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.LuaScript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>strings__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\\.)</string>
          <key>name</key>
          <string>constant.numeric.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.)</string>
          <key>name</key>
          <string>string.LuaScript</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
