<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array>
    <string>gs</string>
   </array>
  <key>name</key>
  <string>goscript</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.goscript</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>\b(constructor)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.goscript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.goscript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#lua</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#SELF</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#strings</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numbers</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>^(@compile|@nolib)\b</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.goscript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.goscript</string>
          <key>end</key>
          <string>($)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.goscript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(break|do|else|elseif|let|repeat|return|while|new)\b</string>
          <key>name</key>
          <string>keyword.goscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(#)(?=[\w\d._]+\b)</string>
          <key>name</key>
          <string>constant.numeric.goscript</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>^(prototype)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.goscript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\)?)(:)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.goscript</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>is.operator.goscript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>\b(for)\b</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.goscript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\)?)(:)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.goscript</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>is.operator.goscript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>\b(foreach)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.goscript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\)?)(:)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.goscript</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>is.operator.goscript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(func\s+)([\w\d_\.]+)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.goscript</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.language.goscript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__7</string>
            </dict>
           </array>
          <key>end</key>
          <string>(:|$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>is.operator.goscript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(if\s+)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.goscript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__8</string>
            </dict>
           </array>
          <key>end</key>
          <string>($)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.goscript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.goscript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__9</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.goscript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.goscript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__10</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.goscript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>SELF</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b(self)\b</string>
          <key>name</key>
          <string>string.goscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.\.\.?)</string>
          <key>name</key>
          <string>constant.numeric.goscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\:|\?)</string>
          <key>name</key>
          <string>is.operator.goscript</string>
        </dict>
       </array>
    </dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(\-\-\[\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.goscript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.goscript</string>
          <key>end</key>
          <string>(\-\-\]\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.goscript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&apos;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.goscript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.goscript</string>
          <key>end</key>
          <string>($)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.goscript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>comments__1</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>comments__2</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>lua</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b(nil|true|false|math.pi)\b</string>
          <key>name</key>
          <string>constant.numeric.goscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(String|Number|Array|Math|System)\b(?=\.|\()</string>
          <key>name</key>
          <string>entity.name.class.goscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(or|and|not)\b</string>
          <key>name</key>
          <string>is.operator.goscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\+|\-|\*|/|//|&lt;=|=|&gt;=|%%|%|\!)</string>
          <key>name</key>
          <string>string.goscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(\:?\.?)([\w\d_]+(?=\())</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.goscript</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.goscript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(\.)([\w\d_]+)\b</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.goscript</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.language.goscript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(assert|collectgarbage|dofile|error|getfenv|getmetatable|ipairs|loadfile|loadstring|module|next|pairs|pcall|print|rawequal|rawget|rawset|require|select|setfenv|setmetatable|tonumber|tostring|type|unpack|xpcall)\b(?=\[\[|\()</string>
          <key>name</key>
          <string>entity.name.function.goscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(coroutine\.(create|resume|running|status|wrap|yield)|string\.(byte|char|dump|find|format|gmatch|gsub|len|lower|match|rep|reverse|sub|upper)|table\.(concat|insert|maxn|remove|sort)|math\.(abs|acos|asin|atan2?|ceil|cosh?|deg|exp|floor|fmod|frexp|ldexp|log|log10|max|min|modf|pow|rad|random|randomseed|sinh?|sqrt|tanh?)|io\.(close|flush|input|lines|open|output|popen|read|tmpfile|type|write)|os\.(clock|date|difftime|execute|exit|getenv|remove|rename|setlocale|time|tmpname)|package\.(cpath|loaded|loadlib|path|preload|seeall)|debug\.(debug|[gs]etfenv|[gs]ethook|getinfo|[gs]etlocal|[gs]etmetatable|getregistry|[gs]etupvalue|traceback|upvaluejoin))\b(?=\s*(?:[\x\x{007b}0028\x{007d}\x\x{007b}007b\x{007d}\&amp;quot\x{003b}\x\x{007b}0027\x{007d}]|\[\[|\())</string>
          <key>name</key>
          <string>entity.name.function.goscript</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\w+)</string>
          <key>name</key>
          <string>constant.numeric.goscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\()</string>
          <key>name</key>
          <string>text.goscript</string>
        </dict>
       </array>
    </dict>
    <key>main__10</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#lua</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#SELF</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#strings</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numbers</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b(is\s+)([\w\d_]+)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.goscript</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.other.inherited-class.goscript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([\w\d_]+)</string>
          <key>name</key>
          <string>entity.name.class.goscript</string>
        </dict>
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#lua</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#strings</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numbers</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(let)\b</string>
          <key>name</key>
          <string>keyword.goscript</string>
        </dict>
       </array>
    </dict>
    <key>main__5</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#lua</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#strings</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numbers</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(in)\b</string>
          <key>name</key>
          <string>keyword.goscript</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.goscript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__6</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.goscript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>main__6</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b([\w\d_]+)</string>
          <key>name</key>
          <string>variable.language.goscript</string>
        </dict>
       </array>
    </dict>
    <key>main__7</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#SELF</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+)</string>
          <key>name</key>
          <string>constant.numeric.goscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\()</string>
          <key>name</key>
          <string>text.goscript</string>
        </dict>
       </array>
    </dict>
    <key>main__8</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\?|:)</string>
          <key>name</key>
          <string>is.operator.goscript</string>
        </dict>
       </array>
    </dict>
    <key>main__9</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>numbers</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(0[xX][0-9a-fA-F]+)</string>
          <key>name</key>
          <string>constant.numeric.goscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\-\d*\.?\d+|\b\d*\.?\d+)</string>
          <key>name</key>
          <string>constant.numeric.goscript</string>
        </dict>
       </array>
    </dict>
    <key>strings</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.goscript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#strings__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.goscript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>strings__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\\.)</string>
          <key>name</key>
          <string>constant.numeric.goscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.)</string>
          <key>name</key>
          <string>string.goscript</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
